### ISSUE TITLE
Can't bind to 'ngxFileDropzone' since it isn't a known property

### ISSUE THREAD

**Issue by tirlipinpon** [fvilers/ngx-file-helpers#6] opened 2018-04-05 12:58 UTC
Imported the FileHelpersModule into my module with  "ngx-file-helpers": "^1.0.0-alpha.5", version.

If i use it on simple directive (ngxFileDropzone) i not complain.

But i i use it with the input decorator:  [ngxFileDropzone]="readMode" on a div : 
Can't bind to 'ngxFileDropzone' since it isn't a known property of 'div'. ("

Wathever both case, if i drag on it it seem not working.

ps: was so happy with the old "angular-file-dropzone": "^1.0.2",   working version.

**Comment by fvilers** [comment] 2018-04-06 07:15
I'm sorry to read that you have some difficulties since I merged the two projects. I'll see what I can do to help you. Could you make a reproduction on StackBlitz?

From what I can see on this demo (https://stackblitz.com/edit/ngx-file-helpers-demo?file=app%2Ffile-dropzone-demo%2Ffile-dropzone-demo.component.html), the binding is working.

**Comment by adyba** [comment] 2018-04-18 15:49
I have the same problem with ngxFilePicker. The problem is not the code the problem is the NMP package. The content of the NPM instalation is not complete (or is somehow weirdly pre-compiled) so the webpack on our machines is not capable to recompile and use your TS code. 

After `npm install --save ngx-file-helpers` my `/node-modules/ngx-file-helpers/src` has only `file-dropzone.directive.d.ts` but no `file-dropzone.directive.ts` etc.

**Comment by fvilers** [comment] 2018-04-23 07:50
Hi, could you remove the package using `npm remove ngx-file-helpers`? Then ensure that the module has correctly removed from the  `node_modules`  directory and from your `package.json`file. Then, try to install it again and let me know if the issue persists.

**Comment by adyba** [comment] 2018-04-24 18:07
Hi, 
I have deleted via remove and also manually deleting the folder from `node_modules` installed again with the same result. Try to edit the build scripts inside 'package.json'. Your modified scripts are somehow designed to get a standalone JS files which is good for development & testing but when I start 'ng serve | ionic serve' or `whatever build` I need a standard build that can be recognized by a project master build that is more interested in source `.ts` than final `.js`

**Comment by fvilers** [comment] 2018-04-29 14:50
That's strange. Do you encounter the same issue with an out of the box Angular project created using @angular/cli (not an Ionic one)?

**Comment by adyba** [comment] 2018-05-02 07:54
Fabian, I do appreciate you effort and as I said, the code seems to be OK but  
an average Angular/Ionic module build script is `"build": "rm -rf aot dist && ngc"`
whereas your build script is `"build": "npm run clean && npm run build:esm2015 && npm run build:fesm2015 && npm run build:esm5 && npm run build:fesm5 && npm run build:umd && npm run build:umd:min && npm run copy:assets"`  _[package.json](https://github.com/fvilers/ngx-file-helpers/blob/master/package.json) line 18_
I'm NOT an `npm` expert I can only tell when something doesn't work. I can only guess whats going on.
My best guess is that your build script builds things that cannot be integrated into our Ionic builds. 
Your goal as a `npm package` author is NOT the `esm5 code`, but the typescript that can be seamlessly integrated (imported and tree-shaked) into our typescript code. When I type `ionic build`  or `ionic serve` a build script of every npm package is executed. An average Ionic component deletes all pre-compiled stuff and gives the steering wheel to `ngc` (a linkage utility ?????). Your build script builds more and more monolithic JS staff, that doesn't fit the final (complete Ionic application) package.

**Comment by fvilers** [comment] 2018-05-02 07:58
OK, I see. It looks like this library is totally incompatible with Ionic. I should try to build an Ionic app by myself to understand how it goes. And then, try to adapt the building system of the library. But, in the meantime, this lib is working pretty well with "standard" Angular apps. So don't expect me to fix it soon as I have a ton of other projects to work on.

**Closed** 2020-02-11 14:42 UTC
